// Mocks generated by Mockito 5.4.1 from annotations
// in charge_station_finder/test/bloc_tests/auth_bloc_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:charge_station_finder/application/core/failure.dart' as _i5;
import 'package:charge_station_finder/domain/auth/models/noReturn.dart' as _i8;
import 'package:charge_station_finder/domain/auth/models/signInFormForm.dart'
    as _i7;
import 'package:charge_station_finder/domain/auth/models/signUpForm.dart'
    as _i9;
import 'package:charge_station_finder/domain/contracts/IAuthRepository.dart'
    as _i3;
import 'package:charge_station_finder/infrastructure/dto/userAuthCredential.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthenticationRepository extends _i1.Mock
    implements _i3.IAuthenticationRepository {
  MockIAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>> login(
          {required _i7.SignInForm? signInForm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#signInForm: signInForm},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserData>(
          this,
          Invocation.method(
            #login,
            [],
            {#signInForm: signInForm},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>> logout() =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>.value(
            _FakeEither_0<_i5.Failure, _i8.NoReturns>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>> getUserAuthCredential() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAuthCredential,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserData>(
          this,
          Invocation.method(
            #getUserAuthCredential,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserData>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>> signUp(
          {required _i9.SignUpForm? signUpForm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {#signUpForm: signUpForm},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>.value(
            _FakeEither_0<_i5.Failure, _i8.NoReturns>(
          this,
          Invocation.method(
            #signUp,
            [],
            {#signUpForm: signUpForm},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>> deleteAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>.value(
            _FakeEither_0<_i5.Failure, _i8.NoReturns>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>> changePassword({
    required String? otpToken,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #otpToken: otpToken,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>.value(
            _FakeEither_0<_i5.Failure, _i8.NoReturns>(
          this,
          Invocation.method(
            #changePassword,
            [],
            {
              #otpToken: otpToken,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.NoReturns>>);
}
